# -*- coding: utf-8 -*-
"""Motor+Vehicle+Thefts Maven Analytics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zfhR_Z47ulMnyzX2mc9495INrJmi17Lw
"""

##Preparing Motor Vehicle Thefts Dataset for Interactive Power BI Dashboard Creation
##Dataset credit goes to Maven Analytics

##importing pandas, matplotlib and numpy libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

# reading the dataframe

Data = pd.read_csv('/content/stolen_vehicles.csv')

Data

#saving a copy of original dataset
svdata = Data.copy()

svdata

svdata.sample(5)

svdata.shape

svdata.info()

svdata.isnull().any()

#checking for number of null vaules in dataset
svdata.isnull().sum()

#converting date_stolen column from object data type to date data type
svdata.date_stolen = pd.to_datetime(svdata.date_stolen)

svdata.info()

duplicate_values = svdata['vehicle_id'].duplicated()
print(duplicate_values)

#checking for duplicate records in the primary key
svdata['vehicle_id'].is_unique

##check rows with nan values
nan_svdata = svdata.isna()
nan_svdata

#drop rows with missing records
svclean = svdata.dropna()
svclean

svclean.info()

svclean.vehicle_type.unique()

svclean.color.unique()

svcleanbi = svclean.copy()

svcleanbi

svcleanbi.to_csv('svcleanbi.csv', index=False)
