  # -*- coding: utf-8 -*-


Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BTaYG9Z_lhQpIHSBTQLk7aa_gdJb-3uH

# New section
"""

5 + 9

Greeting = 'Hello World'
greeting = 'hello world'

print(Greeting)
print(greeting)

print('Hello World. I am Boluwatife !!!')

# Find the perimeter of a square with length size of 4
4*4

print(greeting)

def SI():
  P = 2500000
  R = 0.03
  T = 5
  SIMPLE_INTEREST = P*R*T
  print(SIMPLE_INTEREST)

SI()

P = int(input('what is P'))
R = float(input('what is R'))
T = int(input('what is  T'))
SIMPLE_INTEREST = P*R*T
print('The SIMPLE_INTEREST is:', SIMPLE_INTEREST)

Principal = int(input('what is Principal '))
Rate = float(input('what is Rate '))
Time = int(input('what is  Time '))
SIMPLE_INTEREST = Principal*Rate*Time
print(f'The SIMPLE_INTEREST for {Principal}, {Rate} and {Time} is:', SIMPLE_INTEREST)

###Create a program that takes two numbers as input and performs basic arithmetic operations (addition, subtraction, multiplication, division).

FirstNumber = float(input('Can you please tell me your first value? '))
SecondNumber = float(input('Would you like to please tell me your second value? '))
Functions = (input('What function would you like me to perform for you? '))
BasicFunctions = FirstNumber, Functions, SecondNumber
print(f'The Addition of {FirstNumber} and {SecondNumber} is:', BasicFunctions)

FirstNumber = float(input('Can you please tell me your first value? '))
SecondNumber = float(input('Would you like to please tell me your second value? '))
BasicFunctions = FirstNumber + SecondNumber
print(f'The Addition of {FirstNumber} and {SecondNumber} is:', BasicFunctions)

FirstNumber = float(input('Can you please tell me your first value? '))
SecondNumber = float(input('Would you like to please tell me your second value? '))
Functions = input('Would you like to do addition, subtraction, multiplication or division? ')
addition = FirstNumber + SecondNumber
subtraction = FirstNumber - SecondNumber
multiplication = FirstNumber * SecondNumber
division = FirstNumber / SecondNumber
if Functions == addition:
    print(f'The addition of {FirstNumber} and {SecondNumber} is:', addition)
elif Functions == subtraction:
  print(f'The subtraction of {FirstNumber} and {SecondNumber} is:', subtraction)
elif Functions == multiplication:
  print(f'The multiplication of {FirstNumber} and {SecondNumber} is:', multiplication)
else:
  print(f'The division of {FirstNumber} and {SecondNumber} is:', division)

FirstNumber = float(input('Can you please tell me your first value? '))
SecondNumber = float(input('Would you like to please tell me your second value? '))
Functions = (input('Would you like to do addition, subtraction, multiplication or division? '))
addition = FirstNumber + SecondNumber
subtraction = FirstNumber - SecondNumber
multiplication = FirstNumber * SecondNumber
division = FirstNumber / SecondNumber
print(f'The addition of {FirstNumber} and {SecondNumber} is:', addition)
print(f'The subtraction of {FirstNumber} and {SecondNumber} is:', subtraction)
print(f'The multiplication of {FirstNumber} and {SecondNumber} is:', multiplication)
print(f'The division of {FirstNumber} and {SecondNumber} is:', division)



FirstNumber = float(input('Can you please tell me your first value? '))
SecondNumber = float(input('Would you like to please tell me your second value? '))
addition = FirstNumber + SecondNumber
subtraction = FirstNumber - SecondNumber
multiplication = FirstNumber * SecondNumber
division = FirstNumber / SecondNumber
print(f'The addition of {FirstNumber} and {SecondNumber} is:', addition)
print(f'The subtraction of {FirstNumber} and {SecondNumber} is:', subtraction)
print(f'The multiplication of {FirstNumber} and {SecondNumber} is:', multiplication)
print(f'The division of {FirstNumber} and {SecondNumber} is:', division)



def SI():
  P = 2500000
  R = 0.03
  T = 5
  SIMPLE_INTEREST = P*R*T
  print(SIMPLE_INTEREST)

SI()



##Find the perimeter of a square as a function and make the code as interactive as possible

def SP():
  SquareLenght = float(input('Can you remember the lenght of the square you want me to assist you with? '))
  Unit = input('What unit was it? ')
  SquareSides = 4
  SquarePerimeter = SquareLenght*SquareSides
  print('Hi, the perimeter of the square you need assistance with is:', SquarePerimeter, Unit)

SP()

###just space

SquareLenght = float(input('Can you remember the lenght of the square you described to me? '))
Unit = input('How is the unit of measurement? ')
SquareSides = 4
SquarePerimeter = SquareLenght*SquareSides
print('My friend, the perimeter of the square you have just described is:', SquarePerimeter, Unit)



Cole = 500
Nicole = 700
Derek = 1000
sum = Cole + Nicole + Derek
print('£',sum)

#string slicing
Words = 'String slicing return a range of character from a string. This is achieved by specifiying the start index and end index separated by a colon'
print(Words[:57])

Words.capitalize()

me = 'Daramola Boluwatife'

me.find('D')

me = 'Daramola Boluwatife'
len(me)

print('Dara' in me)

myFruit = ['Apple', 'Orange', 'Grapes','Mango', 'PineApple', 'Banana']

len(myFruit)

myFruit[3]

print(myFruit[3])

type(myFruit)

myFruit.append('Tea')
myFruit

myFruit.extend(['Guava','Pawpaw'])
myFruit

print(myFruit)

myFruit.pop(4)

myFruit

myFruit.remove('Grapes')

myFruit

myFruit.index('Mango')

myFruit.reverse()

myFruit

myFruit.sort()

myFruit



Age = int(input('Enter your Age:'))
if Age >= 18:
  print('You are an adult.')
  print('You are qualified for a DL.')
else:
  print('You are a minor.')
  print('You are Not qualified for a DL')

###Write a program that takes as input from the keyboard the monthly salary of a staff.
###You are to print 'You earn more than an average salary' where the salary is above 40000. Else, print 'You earn below an average salary'

Staff_Salary = float(input('What do you earn monthly?'))
if Staff_Salary>40000:
  print('You earn more than an average salary')
else:
  print('You earn below an average salary')

Principals = float(input('Enter the principals amount:'))
years = float(input('Enter the number of years:'))
if years <= 3:
  rate = 0.03
elif years > 7:
  rate = 0.06
else:
  rate = 0.05
interest = Principals * rate * years
print (f"You are owing £{interest}")

from os import PRIO_PGRP
Years = int(input('Enter the year:\n'))
p = float(input('Enter the principal:|n'))
if Years <= 3:
  rate = 0.03
elif Years >= 4 and Years <= 7:
  rate = 0.05
else:
  rate = 0.06
si = p * Years * rate
print(si)

###Write a program that takes the marital status of a person as input. The program is to print 'You qualify for a double ticket' if the status is married.
###It should print' You do not qualify for a double ticket' if status is single. Any other gender should get an output of 'Invalid gender for this event'

status = input("Hello, what's your marital status?")
if status.lower() == 'married':
  print('You qualify for a double ticket')
elif status.lower() == 'single':
  print('You do not qualify for a double ticket')
else:
  print('Invalid gender for this event')

status = input("Hello, what's your marital status?")
if status == 'married':
  print('You qualify for a double ticket')
elif status == 'single':
  print('You do not qualify for a double ticket')
else:
  print('Invalid gender for this event')

###Write a program using the if- elif statement that gives Rice pudding to persons age between 0 and 3.
###It gives Doughnut to ages 4 to 9 and gives 'Tabioka' to children ages 10 to 17.
###Others are adults and they should get a prompt that tells them to go eat at home.

Ages = int(input('Hi, please what is your age?'))
if Ages <= 3:
  print('come for your rice pudding')
elif Ages <= 9:
  print('come and have your doughnut')
elif Ages <= 17:
  print('come for tabioka')
else:
  print('go home to eat')

###Create a program that takes two numbers as input and performs basic arithmetic operations (addition, subtraction, multiplication, division).

FirstNumber = float(input('Can you please tell me your first value? '))
SecondNumber = float(input('Would you like to please tell me your second value? '))
Functions = input('Would you like to do addition, subtraction, multiplication or division? ')
#addition = FirstNumber + SecondNumber
#subtraction = FirstNumber - SecondNumber
#multiplication = FirstNumber * SecondNumber
#division = FirstNumber / SecondNumber
if Functions.lower() == 'addition':
    print(f'The addition of {FirstNumber} and {SecondNumber} is:', FirstNumber + SecondNumber)
elif Functions.lower() == 'subtraction':
  print(f'The subtraction of {FirstNumber} and {SecondNumber} is:', FirstNumber - SecondNumber)
elif Functions.lower() == 'multiplication':
  print(f'The multiplication of {FirstNumber} and {SecondNumber} is:', FirstNumber * SecondNumber)
else:
  print(f'The division of {FirstNumber} and {SecondNumber} is:', FirstNumber / SecondNumber)

age = int(input('Enter the age: '))
status = input("Hello, what's your marital status? ")
if status.lower() == 'married':
  print('You qualify for a double ticket')
elif status.lower() == 'single':
  print('You do not qualify for a double ticket')
else:
  print('Invalid gender for this event')

AgesS = int(input('Hi, please what is your age?'))
if AgesS >= 0 and AgesS <= 3:
  print('come for your rice pudding')
elif AgesS >= 4 and AgesS <= 9:
  print('come and have your doughnut')
elif AgesS >= 10 and AgesS <= 17:
  print('come for tabioka')
elif AgesS < 0:
  print ('you have not been born yet')
else:
  print('go home to eat')

for x in range (6):
  Ages = int(input('Hi, please what is your age?'))
  if Ages <= 3:
    print('come for your rice pudding')
  elif Ages <= 9:
    print('come and have your doughnut')
  elif Ages <= 17:
    print('come for tabioka')
  else:
    print('go home to eat')

sum1 = 0
for x in range (1,20,2):
  print(x)
  sum1 = sum1 + x
print('Total sum is', sum1)

age = int(input('Enter the age: '))
status = input("Hello, what's your marital status? ")
if status.lower() == 'married':
  print('You qualify for a double ticket')
elif status.lower() == 'single':
  print('You do not qualify for a double ticket')
else:
  print('Invalid gender for this event')



"""Pandas"""

from google.colab import drive
drive.mount('/content/drive')

##import pandas library
import pandas as pd

#read in our dataframe

SalesData = pd.read_csv('/content/drive/MyDrive/Sales_Orders GSQ2..csv')

SalesData

SalesData.head(20)

SalesData.describe()

SalesData.info()

SalesData.columns

data = SalesData.copy()

data

"""Data Cleaning"""

#drop a column
data = data.drop(columns = 'GDSOrder Date')

data

#to check for missing data
data.isnull().sum()

data.isnull()

"""To check for duplicates"""

duplicates_row = data[data.duplicated()]

duplicates_row = data[data.duplicated()]
duplicates_row

duplicates_row = data[data.duplicated()]
print('The duplicates are below:')
print(duplicates_row)

duplicates_row = data[data.duplicated()]
print('The duplicates are below:')
duplicates_row

"""To rename"""

data.rename(columns={'item':'Item'}, inplace=True)
data

data.info()

#convert column to date
data['Order Date'] = pd.to_datetime(data['Order Date'])

data.info()

#Extracting the month name and creating a new column
data['Month Name'] = data['Order Date'].dt.month_name()

data

#Extracting the quarter and creating a new column
data['Quarter'] = data['Order Date'].dt.quarter

data

#Split the first and lastname
data['FirstName'] = data['Customer Name'].str.split(' ', 1).str[0]
data['LastName'] = data['Customer Name'].str.split(' ', 1).str[1]

data

#drop a column
#data.drop('Customer Name', axis = 1, inplace = True)
#axis = 1 for column, 0 for row
data = data.drop(columns = 'Customer Name')

data

"""Check for unique values in a column"""

#data['City].unique()
data.City.unique()

data['City'].value_counts

"""Replacing values"""

#convert to title case
data['City'] = data['City'].str.title()

#To convert the sale column to numeric
data['Sale'] = pd.to_numeric (data['Sale'].replace('[\$]','',regex=True).replace(',','',regex=True))

data['Item Cost'] = pd.to_numeric (data['Item Cost'].replace('[\$]','',regex=True).replace(',','',regex=True))

data.info()

#Find profit per item
data['Profit per Item'] = data['Sale'] - data['Item Cost']

data

#Find Total profit
data['Total Profit'] = data['Profit per Item'] * data['Unit Sold']

data

"""Rearranging columns as desired"""

data.columns

data = data[['Order ID', 'Order Date', 'FirstName', 'LastName', 'Year', 'City', 'State', 'Country', 'Region',
       'Segment', 'Item', 'Month Name', 'Sale', 'Item Cost', 'Unit Sold',
       'Quarter', 'Profit per Item', 'Total Profit']]

data



"""Python Visualization"""

